apiVersion: v1
kind: PersistentVolume
metadata:
  name: captcha-volume
  labels:
    type: local
    app: tfjob
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data1/k8s_nfs/lsf
    server: store03
