apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: captcha-volume
  namespace: lsf
  labels:
    type: local
    app: tfjob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
